CREATE TABLE MetasVentas (
 MetaID INT IDENTITY PRIMARY KEY,
 ClienteID INT NOT NULL FOREIGN KEY REFERENCES DimCliente(ClienteID),
 ProductoID INT NOT NULL FOREIGN KEY REFERENCES DimProducto(ProductoID),
 Anio INT NOT NULL,
 Mes INT NOT NULL,
 MetaUSD DECIMAL(18,2) NOT NULL
);